server:
  port: ${tomcat.port:${SERVER_PORT:${PORT:8080}}}
  tomcat:
    uri-encoding: UTF-8
spring:
  jpa:
    show-sql: true
    database: MYSQL
    generateDdl: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/user?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
    username: ${db.username}
    password: ${db.password}
    slowSqlMillis: 500
